// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_1wfmGCwW2TEr5HI2-8PVg740_FR5pcQ',
    appId: '1:550834663300:web:a10a75bc2568d6ef8ab7d1',
    messagingSenderId: '550834663300',
    projectId: 'renewmarket-efafd',
    authDomain: 'renewmarket-efafd.firebaseapp.com',
    storageBucket: 'renewmarket-efafd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RmwgCfH2SQUAY9S4svFLZPJqLdQEmOA',
    appId: '1:550834663300:android:599eb9d63e3a96bd8ab7d1',
    messagingSenderId: '550834663300',
    projectId: 'renewmarket-efafd',
    storageBucket: 'renewmarket-efafd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_tooL_2tPOCQMrseaV2fqua8qaFr8vh0',
    appId: '1:550834663300:ios:94a307e25feedb428ab7d1',
    messagingSenderId: '550834663300',
    projectId: 'renewmarket-efafd',
    storageBucket: 'renewmarket-efafd.firebasestorage.app',
    iosBundleId: 'com.example.flutterPad1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tooL_2tPOCQMrseaV2fqua8qaFr8vh0',
    appId: '1:550834663300:ios:94a307e25feedb428ab7d1',
    messagingSenderId: '550834663300',
    projectId: 'renewmarket-efafd',
    storageBucket: 'renewmarket-efafd.firebasestorage.app',
    iosBundleId: 'com.example.flutterPad1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_1wfmGCwW2TEr5HI2-8PVg740_FR5pcQ',
    appId: '1:550834663300:web:063d84edb897b7578ab7d1',
    messagingSenderId: '550834663300',
    projectId: 'renewmarket-efafd',
    authDomain: 'renewmarket-efafd.firebaseapp.com',
    storageBucket: 'renewmarket-efafd.firebasestorage.app',
  );

}